#!/usr/bin/env bash
pids=()

cd app

npm run lint &
pids+=( $! )

npm run check-types &
pids+=( $! )

npm run check-format &
pids+=( $! )

cd ../api

npm run lint &
pids+=( $! )

npm run depcruise &
pids+=( $! )

failures=false

for pid in "${pids[@]}"; do
        printf 'Waiting for %d...' "$pid"
        if ! wait "$pid"; then 
          failures=true
        fi
done

if $failures; then
  exit 1
fi
