# Inserts a blank line between shell prompts
add_newline = true

palette = "custom"

format="$time$battery$all"

[palettes.custom]
orange = "#bf5a01"


[character]
success_symbol = "[➜ ](green)"
error_symbol = "[➜ ](red)"

[aws]
disabled = true

[battery]
disabled = false

[[battery.display]]
threshold = 10
style = "red"

[[battery.display]]
threshold = 30
style = "orange"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"

[directory]
truncation_length = 8
truncation_symbol = "…/"

[docker_context]
only_with_files = false

[time]
disabled=false
format = '[\[$time\]]($style) '
style = 'dimmed'

[username]
style_user = "#A0A5A2 bold"
format =  '[\[$user\]]($style) '
show_always = false 
